# render.yaml
services:
  - type: web
    name: myportfolio-frontend
    env: static
    repo: https://github.com/kai-lucky72/Myportfolio # Replace with your repo
    branch: main
    buildCommand: npm install && npm run build


