services:
  - type: web
    name: lucky-portfolio
    env: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
